/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f34d66f490f1fd5e1b58354654d9ade5)
interface __BaseEnv_Env {
	MENU_IMAGES: KVNamespace;
	CONTENT_DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
